# Generated by Django 4.2 on 2023-06-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="photo",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
